baseURL = "http://willianmano.github.io/"
languageCode = "en-us"
title = "Willian Mano WebSite"

disableKinds = ["taxonomy", "taxonomyTerm"]

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.header]]
  name = "Projects"
  URL = "#projects"
  weight = 3

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 4

[params]
  googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "Willian"
    text2 = "Mano"

  [params.footer]
    copyright = "© Conecti.me. All rights reserved."
    link = "https://conecti.me"